sveltekit: Create supabase endpoints in handle hooks
supabase-community/auth-helpers pull request #163
Opened 2022-07-07 14:26 UTC by david-plugge

This removes the need for user defined endpoints.

2022-07-07 17:19 UTC, jycouet commented
Nice work @david-plugge 

Once this is completed, I would like to use it https://github.com/jycouet/supabase-graphql-example (and upgrade with our latest stuff from GraphQL 😎)

You wanna participate? Ping me 👍

2022-07-08 10:56 UTC, david-plugge commented
To prevent users from creating routes that are handled by this package a warning will be logged if the response status is not 404 or 405.
```js
if (!(res.status === 405 || res.status === 404)) {
  logger.warn(
    `@supabase/auth-helpers-sveltekit handles the route '${endpointPath}'`
  );
}
```

I´m not very convinced by this as the user may return a 404 in his endpoint.
We could also completely ignore sveltekits handlers and just dont call `resolve(event)`.

2022-07-08 22:56 UTC, silentworks requested changes

2022-07-08 22:56 UTC, silentworks commented on packages/sveltekit/src/handlers/user.ts
> +    if (req.method !== 'GET') {
This should be POST and not GET.

2022-07-08 22:56 UTC, silentworks commented on packages/sveltekit/src/handlers/user.ts
> +        Allow: 'GET'
Allowing only POST requests not GET requests.

2022-07-08 22:56 UTC, silentworks commented on packages/svelte/src/SupaAuthHelper.svelte
> +  export let endpointPrefix = '/api/auth';
It's probably worth pulling thru the `ENDPOINT_PREFIX` const from the `@supabase/auth-helpers-shared` package too.

2022-07-08 23:22 UTC, silentworks commented
The callback handler is going to return a 404 because the route doesn't exists and the handler is going to return the status code from that request. We would need to return a new Response with a 200 status code, but this would need to contain the cookie header from the previous response.

2022-07-10 00:29 UTC, silentworks approved these changes

2022-07-10 00:30 UTC, merged

2022-07-10 10:15 UTC, david-plugge commented
@silentworks the packages are not updated, is that intended?